### ISSUE TITLE
Missing definition types for components

### ISSUE THREAD

**Issue by hieuhani** [youngtailors/react-silk#61]
./dist
├── react-silk-ui.es.js
└── react-silk-ui.js

0 directories, 2 files

**Comment by dacsang97** [comment]
Do you run `tsc` after build?

**Comment by dacsang97** [comment]
What the command you use to build?
```
"prebuild": "rimraf dist && tsc",
"build": "rollup -c",
```

I had checked `package.json`, we have `tsc` before `build`.

**Comment by hieuhani** [comment]
Not yet, I just use `yarn dev` to develop.
The error: `TypeScript error: Could not find a declaration file for module 'react-silk-ui'. '/Users/hieuhani/Code/react-silk/packages/react-silk-ui/dist/react-silk-ui.js' implicitly has an 'any' type.` threw

**Comment by hieuhani** [comment]
If it needs to be, please specify in the docs

**Comment by dacsang97** [comment]
I fixed this in #63
